apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./APP/overlay/
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-source
  timeout: 2m0s
  validation: client