apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: testdevops
  # webhook address (ignored if secretRef is specified)
  address: https://hooks.slack.com/services/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
  # HTTP(S) proxy (optional)
  # # secret containing the webhook address (optional)
  # secretRef:
  #   name: webhook-url