apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: testdevops
  # webhook address (ignored if secretRef is specified)
  # address: https://hooks.slack.com/services/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
  # HTTP(S) proxy (optional)
  # # secret containing the webhook address (optional)
  secretRef:
    name: webhook-url