apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: nginx:1.14.1
        name: nginx
