apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 4
  template:
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
